-- Migration 001: Add 8 tools missing from initial seed
-- Generated by: data/scripts/find_missing_tools.py
-- Date: 2026-06-12
-- Source: data/batch-results-parsed.json (100 records) → data/seed.sql (92 rows)
--
-- These 8 records had content_richness in (Error, Minimal) + extraction_confidence == Low
-- and were excluded from the original seed. They are added here for completeness.
-- Embeddings are NULL — they will be generated on first use by the embedding pipeline.
-- All statements use ON CONFLICT (cgspace_id) DO NOTHING for idempotency.
--
-- IDs are deterministic UUIDs (uuid5 of the CGSpace handle URL).


-- 10568-100101: Newton Fund PROPOSAL: Exploiting biodiversity in Brachiaria and Panicum tropical
INSERT INTO public.tools (
    id, title, summary, what_it_does, when_to_use_it, who_its_for,
    pillars, domains, type, stage, target_users, geography,
    authors, date_published, source_url, source_organization,
    cover_image_url, embedding, average_rating, rating_count, view_count,
    cgspace_id, relevance_score, is_visible, created_at, updated_at
) VALUES (
    '203f408d-ead6-5418-959c-c854d16b863c',
    'Newton Fund PROPOSAL: Exploiting biodiversity in Brachiaria and Panicum tropical forage grasses using forward and reverse genetics to improve livelihoods and sustainability. Proposal original profo...',
    'No content was successfully scraped from the source URL Resource appears to be a Newton Fund proposal related to tropical forage grass biodiversity Focus seems to be on using forward and reverse genetics approaches',
    NULL,
    NULL,
    NULL,
    '{"Monitoring, Evaluation and Learning"}',
    '{"Biodiversity"}',
    'Other',
    'Prototype',
    NULL,
    NULL,
    NULL,
    NULL,
    'https://hdl.handle.net/10568/100101',
    'International Center for Tropical Agriculture',
    NULL,
    NULL,
    0, 0, 0,
    '10568-100101',
    0.70,
    true,
    now(), now()
) ON CONFLICT (cgspace_id) DO NOTHING;

-- 10568-100125: Forewarned is Forearmed how Climate Information Services are Saving the Lives an
INSERT INTO public.tools (
    id, title, summary, what_it_does, when_to_use_it, who_its_for,
    pillars, domains, type, stage, target_users, geography,
    authors, date_published, source_url, source_organization,
    cover_image_url, embedding, average_rating, rating_count, view_count,
    cgspace_id, relevance_score, is_visible, created_at, updated_at
) VALUES (
    'c8d8b1bb-1797-5c3e-ad18-2b3517892f9a',
    'Forewarned is Forearmed how Climate Information Services are Saving the Lives and Livelihoods of Senegalese Fisherfolk',
    'This success story documents how climate information services are being used to protect the lives and livelihoods of fisherfolk in Senegal. It appears to be part of a larger FAO publication showcasing climate services and safety nets initiatives under the CCAFS program.',
    NULL,
    NULL,
    'Development practitioners and policymakers interested in climate services for fishing communities',
    '{"Monitoring, Evaluation and Learning"}',
    '{"Climate Resilience"}',
    'Case Study',
    'Widely Deployed',
    '{"Development practitioners and policymakers interested in climate services for fishing communities"}',
    '{"Senegal","Africa","Western Africa"}',
    NULL,
    NULL,
    'https://hdl.handle.net/10568/100125',
    'Food and Agriculture Organization of the United Nations',
    NULL,
    NULL,
    0, 0, 0,
    '10568-100125',
    0.70,
    true,
    now(), now()
) ON CONFLICT (cgspace_id) DO NOTHING;

-- 10568-100243: Gendered Feed Assessment Tool (G-FEAST) focus group discussion guide
INSERT INTO public.tools (
    id, title, summary, what_it_does, when_to_use_it, who_its_for,
    pillars, domains, type, stage, target_users, geography,
    authors, date_published, source_url, source_organization,
    cover_image_url, embedding, average_rating, rating_count, view_count,
    cgspace_id, relevance_score, is_visible, created_at, updated_at
) VALUES (
    '2e6702c8-d930-5e03-8b71-e1f3094be5d8',
    'Gendered Feed Assessment Tool (G-FEAST) focus group discussion guide',
    'The Gendered Feed Assessment Tool (G-FEAST) focus group discussion guide is a methodological tool designed to assess livestock feeding practices through a gender lens. It provides structured guidance for conducting focus group discussions to understand how gender dynamics influence feed-related decision-making and practices in livestock systems.',
    'Provides structured guidance for conducting focus group discussions to assess livestock feeding practices with attention to gender roles and decision-making patterns.',
    NULL,
    'Scientists and researchers conducting livestock feed assessments',
    '{"Gender Equality and Social Inclusion","Monitoring, Evaluation and Learning"}',
    '{"Livestock","Agri-Food Systems"}',
    'Guidelines',
    'Prototype',
    '{"Scientists and researchers conducting livestock feed assessments"}',
    NULL,
    NULL,
    NULL,
    'https://hdl.handle.net/10568/100243',
    'International Livestock Research Institute',
    NULL,
    NULL,
    0, 0, 0,
    '10568-100243',
    0.70,
    true,
    now(), now()
) ON CONFLICT (cgspace_id) DO NOTHING;

-- 10568-100244: Gendered Feed Assessment Tool (G-FEAST) individual farmer interview questionnair
INSERT INTO public.tools (
    id, title, summary, what_it_does, when_to_use_it, who_its_for,
    pillars, domains, type, stage, target_users, geography,
    authors, date_published, source_url, source_organization,
    cover_image_url, embedding, average_rating, rating_count, view_count,
    cgspace_id, relevance_score, is_visible, created_at, updated_at
) VALUES (
    '6e9601e9-4f97-5e54-8a1f-2b2c8753878b',
    'Gendered Feed Assessment Tool (G-FEAST) individual farmer interview questionnaire',
    'The Gendered Feed Assessment Tool (G-FEAST) individual farmer interview questionnaire is a data collection instrument designed to assess livestock feeding practices through a gender lens. It enables researchers and practitioners to gather information about how men and women farmers differently engage with livestock feed resources, decision-making, and management practices.',
    'The tool uses structured individual interviews to collect gender-disaggregated data on livestock feeding practices and decision-making processes.',
    NULL,
    'Researchers and development practitioners working on livestock systems',
    '{"Gender Equality and Social Inclusion","Monitoring, Evaluation and Learning"}',
    '{"Livestock"}',
    'Tool',
    'Prototype',
    '{"Researchers and development practitioners working on livestock systems"}',
    NULL,
    NULL,
    NULL,
    'https://hdl.handle.net/10568/100244',
    'International Livestock Research Institute',
    NULL,
    NULL,
    0, 0, 0,
    '10568-100244',
    0.70,
    true,
    now(), now()
) ON CONFLICT (cgspace_id) DO NOTHING;

-- 10568-100373: Photo report on the Africa RISING Program Learning Event in Malawi, 5-8 February
INSERT INTO public.tools (
    id, title, summary, what_it_does, when_to_use_it, who_its_for,
    pillars, domains, type, stage, target_users, geography,
    authors, date_published, source_url, source_organization,
    cover_image_url, embedding, average_rating, rating_count, view_count,
    cgspace_id, relevance_score, is_visible, created_at, updated_at
) VALUES (
    '205303b9-8bbe-5df8-9118-71ba99468a3f',
    'Photo report on the Africa RISING Program Learning Event in Malawi, 5-8 February 2019',
    'This is a photo report documenting the Africa RISING Program Learning Event held in Malawi from February 5-8, 2019. The resource appears to be a visual documentation of program activities, learnings, and outcomes from this multi-stakeholder learning event focused on agricultural development in Africa.',
    NULL,
    NULL,
    'Scientists and agricultural development practitioners',
    '{"Monitoring, Evaluation and Learning"}',
    '{"Agri-Food Systems","Livestock"}',
    'Report',
    'Prototype',
    '{"Scientists and agricultural development practitioners"}',
    '{"Malawi","Africa"}',
    NULL,
    NULL,
    'https://hdl.handle.net/10568/100373',
    'International Livestock Research Institute',
    NULL,
    NULL,
    0, 0, 0,
    '10568-100373',
    0.70,
    true,
    now(), now()
) ON CONFLICT (cgspace_id) DO NOTHING;

-- 10568-100488: Livestock headwinds: Help or hindrance to sustainable development?
INSERT INTO public.tools (
    id, title, summary, what_it_does, when_to_use_it, who_its_for,
    pillars, domains, type, stage, target_users, geography,
    authors, date_published, source_url, source_organization,
    cover_image_url, embedding, average_rating, rating_count, view_count,
    cgspace_id, relevance_score, is_visible, created_at, updated_at
) VALUES (
    'c3f39278-c6e5-5ed6-8b65-daad58fae212',
    'Livestock headwinds: Help or hindrance to sustainable development?',
    'This appears to be a presentation examining the complex relationship between livestock systems and sustainable development goals. The resource explores whether livestock production serves as a help or hindrance to achieving sustainable development outcomes.',
    NULL,
    NULL,
    'Scientists and researchers',
    '{"Monitoring, Evaluation and Learning"}',
    '{"Livestock","Agri-Food Systems"}',
    'Presentation',
    'Prototype',
    '{"Scientists and researchers"}',
    NULL,
    NULL,
    NULL,
    'https://hdl.handle.net/10568/100488',
    'International Livestock Research Institute',
    NULL,
    NULL,
    0, 0, 0,
    '10568-100488',
    0.70,
    true,
    now(), now()
) ON CONFLICT (cgspace_id) DO NOTHING;

-- 10568-100562: Digitising farmer cooperatives to improve their financial and operational effici
INSERT INTO public.tools (
    id, title, summary, what_it_does, when_to_use_it, who_its_for,
    pillars, domains, type, stage, target_users, geography,
    authors, date_published, source_url, source_organization,
    cover_image_url, embedding, average_rating, rating_count, view_count,
    cgspace_id, relevance_score, is_visible, created_at, updated_at
) VALUES (
    '61c736cc-08be-5a84-b50d-d50db1455012',
    'Digitising farmer cooperatives to improve their financial and operational efficiency',
    'This resource documents the digitization of farmer cooperatives to enhance their financial and operational efficiency. It appears to be an experience capitalization piece that explores how digital technologies and ICT solutions can transform cooperative management and business operations in agricultural contexts.',
    NULL,
    NULL,
    'Development practitioners working with farmer cooperatives',
    '{"Digital and Financial Services","Monitoring, Evaluation and Learning"}',
    '{"Agri-Food Systems","Value Chains"}',
    'Case Study',
    'Prototype',
    '{"Development practitioners working with farmer cooperatives"}',
    NULL,
    NULL,
    NULL,
    'https://hdl.handle.net/10568/100562',
    'Technical Centre for Agricultural and Rural Cooperation',
    NULL,
    NULL,
    0, 0, 0,
    '10568-100562',
    0.70,
    true,
    now(), now()
) ON CONFLICT (cgspace_id) DO NOTHING;

-- 10568-100592: Gender and digitalisation supporting women in agribusiness
INSERT INTO public.tools (
    id, title, summary, what_it_does, when_to_use_it, who_its_for,
    pillars, domains, type, stage, target_users, geography,
    authors, date_published, source_url, source_organization,
    cover_image_url, embedding, average_rating, rating_count, view_count,
    cgspace_id, relevance_score, is_visible, created_at, updated_at
) VALUES (
    '0f1112b2-18e6-537c-948d-113fce4be8c5',
    'Gender and digitalisation supporting women in agribusiness',
    'This resource examines the intersection of gender and digitalization in supporting women''s participation in agribusiness. It appears to focus on how digital technologies can be leveraged to address gender-specific barriers and enhance women''s roles in agricultural value chains.',
    NULL,
    NULL,
    'Development practitioners working on gender and digitalization in agriculture',
    '{"Gender Equality and Social Inclusion","Digital and Financial Services","Market Systems"}',
    '{"Agri-Food Systems","Value Chains"}',
    'Other',
    'Prototype',
    '{"Development practitioners working on gender and digitalization in agriculture"}',
    NULL,
    NULL,
    NULL,
    'https://hdl.handle.net/10568/100592',
    'CTA (Technical Centre for Agricultural and Rural Cooperation)',
    NULL,
    NULL,
    0, 0, 0,
    '10568-100592',
    0.70,
    true,
    now(), now()
) ON CONFLICT (cgspace_id) DO NOTHING;
